include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

test.pkg:
  stage: verify
  tags: [ "arch:amd64" ]
  image: registry.ddbuild.io/images/mirror/library/golang:1.23.5
  variables:
    GOTOOLCHAIN: "auto"
    KUBERNETES_CPU_REQUEST: "4"
    KUBERNETES_MEMORY_REQUEST: "8Gi"
    KUBERNETES_MEMORY_LIMIT: "8Gi"
  script:
    - make test.pkg

test.cmd:
  stage: verify
  tags: [ "arch:amd64" ]
  image: registry.ddbuild.io/images/mirror/library/golang:1.23.5
  variables:
    GOTOOLCHAIN: "auto"
    KUBERNETES_CPU_REQUEST: "4"
    KUBERNETES_MEMORY_REQUEST: "8Gi"
    KUBERNETES_MEMORY_LIMIT: "8Gi"
  script:
    - make test.cmd

test.meta.core:
  stage: verify
  tags: [ "arch:amd64" ]
  image: registry.ddbuild.io/images/mirror/library/golang:1.23.5
  variables:
    GOTOOLCHAIN: "auto"
    KUBERNETES_CPU_REQUEST: "4"
    KUBERNETES_MEMORY_REQUEST: "8Gi"
    KUBERNETES_MEMORY_LIMIT: "8Gi"
  script:
    - make test.meta.core
